# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from lib import wenet_asr_pb2 as wenet__asr__pb2


class WenetASRStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Test = channel.unary_unary(
                '/wenetasr.WenetASR/Test',
                request_serializer=wenet__asr__pb2.TextMessage.SerializeToString,
                response_deserializer=wenet__asr__pb2.TextMessage.FromString,
                )
        self.Recognize = channel.unary_unary(
                '/wenetasr.WenetASR/Recognize',
                request_serializer=wenet__asr__pb2.RecognizeRequest.SerializeToString,
                response_deserializer=wenet__asr__pb2.RecognizeResponse.FromString,
                )
        self.StreamingRecognize = channel.stream_stream(
                '/wenetasr.WenetASR/StreamingRecognize',
                request_serializer=wenet__asr__pb2.StreamingRecognizeRequest.SerializeToString,
                response_deserializer=wenet__asr__pb2.StreamingRecognizeResponse.FromString,
                )
        self.Punct = channel.unary_unary(
                '/wenetasr.WenetASR/Punct',
                request_serializer=wenet__asr__pb2.TextMessage.SerializeToString,
                response_deserializer=wenet__asr__pb2.TextMessage.FromString,
                )


class WenetASRServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Test(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Recognize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamingRecognize(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Punct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WenetASRServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Test': grpc.unary_unary_rpc_method_handler(
                    servicer.Test,
                    request_deserializer=wenet__asr__pb2.TextMessage.FromString,
                    response_serializer=wenet__asr__pb2.TextMessage.SerializeToString,
            ),
            'Recognize': grpc.unary_unary_rpc_method_handler(
                    servicer.Recognize,
                    request_deserializer=wenet__asr__pb2.RecognizeRequest.FromString,
                    response_serializer=wenet__asr__pb2.RecognizeResponse.SerializeToString,
            ),
            'StreamingRecognize': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamingRecognize,
                    request_deserializer=wenet__asr__pb2.StreamingRecognizeRequest.FromString,
                    response_serializer=wenet__asr__pb2.StreamingRecognizeResponse.SerializeToString,
            ),
            'Punct': grpc.unary_unary_rpc_method_handler(
                    servicer.Punct,
                    request_deserializer=wenet__asr__pb2.TextMessage.FromString,
                    response_serializer=wenet__asr__pb2.TextMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wenetasr.WenetASR', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WenetASR(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Test(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wenetasr.WenetASR/Test',
            wenet__asr__pb2.TextMessage.SerializeToString,
            wenet__asr__pb2.TextMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Recognize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wenetasr.WenetASR/Recognize',
            wenet__asr__pb2.RecognizeRequest.SerializeToString,
            wenet__asr__pb2.RecognizeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamingRecognize(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/wenetasr.WenetASR/StreamingRecognize',
            wenet__asr__pb2.StreamingRecognizeRequest.SerializeToString,
            wenet__asr__pb2.StreamingRecognizeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Punct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wenetasr.WenetASR/Punct',
            wenet__asr__pb2.TextMessage.SerializeToString,
            wenet__asr__pb2.TextMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
